[package]
name = "example-hello"
version = "0.0.0"
publish = false
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
siro = { path = "../.." }

console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
wee_alloc = "0.4"
